[local]
localhost ansible_connection=local ansible_user=ubuntu

[webservers]
web1 ansible_host=IP_DEL_SERVIDOR_WEB1 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/mi-clave.pem

[dbservers]
db1 ansible_host=IP_DEL_SERVIDOR_DB1 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/mi-clave.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
